update createMultipleQuizzz and install new libraries, modified Quizzz
Sawconed/Quizzzee-Server pull request #28
Opened 2024-06-03 03:24 UTC by VinhmqDev

2024-06-04 10:22 UTC, GiaBruh requested changes
Cần thay đổi cấu trúc code.

2024-06-04 10:22 UTC, GiaBruh commented on src/services/quizzzServices.ts
Ông nên tách chức năng này ra thành từng chức năng riêng xử lý cho từng định dạng file.

2024-06-05 01:59 UTC, VinhmqDev commented on src/services/quizzzServices.ts
Included block and unblock quizzzy

2024-06-05 02:24 UTC, GiaBruh approved these changes

2024-06-05 02:24 UTC, merged